Updating author profile as per figma mockups
creativecommons/creativecommons-base pull request #173
Opened 2021-12-13 19:06 UTC by shailee-m

## Fixes
Fixes https://github.com/creativecommons/project_creativecommons.org/issues/142  by @brylie 

## Description
Updated author profile as per figma mockups. Not overriding the vocabulary classes at the moment.

## Checklist
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

2021-12-14 09:24 UTC, brylie requested changes
This looks great overall.

I added a few minor suggestions for readability and a couple of open questions about using `join`.

2021-12-14 09:24 UTC, brylie commented on author.php
> +$author_image_url = get_avatar_url(get_queried_object()->ID, 'squared');
Let's create some context variables for re-use throughout the template code.

```suggestion
$author_object = get_queried_object();
$author_meta = get_user_meta(get_queried_object()->ID);

$author_id = $author_object->ID;
$author_nicename = $author_object->user_nicename;
$author_first_name = $author_meta["first_name"];
$author_position = $author_meta["cc_position"];
$author_description = $author_meta["description"];
$author_image_url = get_avatar_url($author_id, 'squared');
```

2021-12-14 09:24 UTC, brylie commented on author.php
> +				<h2><?php echo get_queried_object()->user_nicename ?></h2>
We can make this code a bit more clear with the previously suggested context variables.
```suggestion
				<h2><?php echo $author_nicename ?></h2>
```

2021-12-14 09:24 UTC, brylie commented on author.php
> +				<p class="mt-2"><?php echo nl2br(join(", ", get_user_meta(get_queried_object()->ID)["description"])) ?></p>
- We can make this code a bit more clear with the previously suggested context variables.
- Is the description field in the author meta stored as a list? I'm just trying to understand the use of `join`.

```suggestion
				<p class="mt-2"><?php echo nl2br(join(", ", $author_description) ?></p>
```

2021-12-14 09:24 UTC, brylie commented on author.php
> +					echo "<h2 class='mb-2'>" . join(" ", get_user_meta(get_queried_object()->ID)["first_name"]) . "'s Posts</h2>";
- let's use the context variable for improved readability
- Why do we use `join` here?

```suggestion
					echo "<h2 class='mb-2'>" . join(" ", $author_first_name) . "'s Posts</h2>";
```

2021-12-14 09:54 UTC, shailee-m commented
@brylie Wordpress is accepting arrays in all keys which is why. We can also just use the first element in the array. I will update the code to do that in case

2021-12-14 09:56 UTC, shailee-m commented
@brylie @annatuma Here is the look of the page after all the updates.
![Untitled_ Dec 14, 2021 3_21 PM (2)](https://user-images.githubusercontent.com/10625985/145975659-d83fa81b-dfb5-4c7d-9e4b-924a8a537878.gif)

2021-12-15 00:02 UTC, brylie commented
@shailee-m, how difficult do you think it might be to use a different image size here? From what I can tell, WordPress seems to be using the 'post-thumbnail` format returned by `the_post`. Is that correct?

I don't want the image format to be a blocking issue in this PR so I'm just asking about the difficulty. We can consider whether the image format needs to change and split that into a follow-up task if needed.

2021-12-17 07:52 UTC, brylie requested changes
This looks good and is ready to merge from what I can see.

The only change would be to resolve the conflict(s).

2021-12-17 15:51 UTC, shailee-m commented
> This looks good and is ready to merge from what I can see.
> 
> The only change would be to resolve the conflict(s).

Resolved conflicts

2021-12-17 19:25 UTC, brylie approved these changes

2021-12-17 19:25 UTC, merged